### ISSUE TITLE
Fix  ChatGPT  and Claude

### ISSUE THREAD

**Issue by lantinglou** [ugorsahin/TalkingHeads#66]
Hello,

Since the ChatGPT and Claude websites have been updated to a new version, the old codes no longer work. Could you please update them?

**Comment by ugorsahin** [comment]
Hello, ChatGPT is functioning properly for me. If you could provide any error messages you're encountering, I'd be happy to investigate further

**Comment by lantinglou** [comment]
hi, sir
Thanks for your reply.
In my case, talkingheads can open Chrome and  visit openai website.

But chatgpt will check if it's a robot, after i manual pass it and type chatgpt username , the Robot check come again and agin, i can't pass it... until about 2mins the program exit....（i use Gemini manual profile method  ）

And also i can not use username and password to login chatgpt automatically.

**Comment by ugorsahin** [comment]
Are you repeatedly attempting to pass through this verification page without success?
![chatgpt](https://github.com/ugorsahin/TalkingHeads/assets/37257227/6128868a-352e-4c71-bf2a-b2ebab6b701e)

You may come across this page due to various factors, such as your IP address, incognito mode, or user agent, or combination of them. Disabling incognito mode or setting headless mode to false may resolve your problem. However, if you're using a VPN, it is most likely to trigger bot detection.

**Comment by lantinglou** [comment]
1. Yes,sir. It is the verification page. and you are correct i am using a VPN.  But i can login and use Chatgpt in a normal Chrome.

2. If this automatically login method still works or we can only login ChatGPT manually like Gemini.
export ChatGPT_UNAME=<your@email>
export ChatGPT_PWD=><password>

from talkingheads import ChatGPTClient
chathead = ChatGPTClient()
response = chathead.interact("Hello, how are you today")
print(response)
